### ISSUE TITLE
Getting Metal Prices

### ISSUE THREAD

**Issue by frederik042853** [Fifteen15Studios/MMM-PreciousMetals#2]
Followed your instructions and did "git pull" to update module and only thing showing up on the display is Header and underneath "Getting Metal Prices..."
What am I missing?

My config file:
{
                        module: "MMM-PreciousMetals",
                                header: "Precious Metals",
                                position: "top_right",
                                config: {                                               // {} This will show gold and silver - the default values
                                        metals: ["gold","silver", "aluminum"],
                                        updateInterval: 30 * 60 * 1000                  //every 30 minutes
                                        }
                },

**Comment by Fifteen15Studios** [comment]
Looks right to me. Have you tried to restart the MM? I know that the commodities (aluminum) won't work until you restart the MM software after the update. The Node-helper won't update until you restart the software (not just refresh the page)

**Comment by frederik042853** [comment]
This is what shows up when I start up MM
[2022-08-03 20:25:12.538] [ERROR]  (node:4827) UnhandledPromiseRejectionWarning: FetchError: request to https://api.metals.live/v1/spot failed, reason: certificate has expired

**Comment by frederik042853** [comment]
Have you had time to check out this issue. I am still getting the same response. I have restarted the Pi, performed a Git Pull.
What else can I do?

**Comment by Fifteen15Studios** [comment]
I have no idea. I took the config code from your comment, put it into my config, and it worked for me:
![image](https://user-images.githubusercontent.com/1030585/187039935-6e202331-c934-4866-8807-2f3738b1a9c1.png)

Maybe completely delete the module from your modules folder, and re-pull it from GitHub? It seems to be an issue with your setup, not the module.

**Comment by Fifteen15Studios** [comment]
The error mentions an expired certificate. Do you have `useHttps: false,` in your config? (Not in the module config, in the main MM config.) Mine has that line, maybe it's a problem with https?

**Comment by frederik042853** [comment]
I do have that line in the mm config file and I have reinstalled the module with the same result. I have quite a few other modules running that have no issues:
camera                   MMM-iFrame          MMM-PreciousMetals  default                  MMM-iFrame-New      MMM-quote-of-the-day internet-monitor         MMM-ImageSlideshow  MMM-RAIN-MAP  MMM-AVStock              MMM-IPCam           MMM-Remote-Control MMM-BackgroundSlideshow  MMM-Lunartic        MMM-SmartWebDisplay MMM-BMW-OW               MMM-MagicMover      MMM-SmartWebDisplay1 MMM-CalendarWeek         MMM-MyCommute       MMM-Snow
MMM-Carousel             MMM-MySenseHat      MMM-Sonos MMM-connection-status    MMM-MyWeather       MMM-Sonos-second MMM-CurrencyExchange     MMM-network-signal  MMM-Stock MMM-DailyBibleVerse      MMM-NewsFeedTicker  MMM-SystemStats MMM-DateCounter          MMM-Oura            mmm-systemtemperature MMM-EasyBack             MMM-page-indicator  MMM-WunderGround MMM-Formula1             MMM-pages           MMM-WunderGround-PWS-Observations
MMM-Globe                MMM-pihole-stats    MMM-WunderGround-PWS-Observations1 MMM-GoogleMapsTraffic    MMM-Pollen          voicecontrol

**Comment by Fifteen15Studios** [comment]
As a troubleshooting step, you may want to navigate to that URL (https://api.metals.live/v1/spot) in a browser to see if it returns what it it supposed to. It should looks something like this:

[{"gold":"1725.65"},{"silver":"19.15"},{"platinum":"893.80"},{"palladium":"2228.55"},{"timestamp":1662947208382}]

Also try https://api.metals.live/v1/spot/commodities as that's where the commodities come from (however, it's likely that you can get to one you can probably get to both.)

If you can't get to that URL in a browser, there's likely something on your network blocking the address
