### ISSUE TITLE
Module can not get prices 

### ISSUE THREAD

**Issue by extremsx** [Fifteen15Studios/MMM-PreciousMetals#3]
Hi there 

First of all thank you for this module. 
It worked fine for at least 6 months. 
Unfortunately since 2 weeks I am getting on the module in the mirror the following message: 
Getting metal prices. 
It seams there is a problem with the page the module is getting the prices from, because if you go to the page 
https://api.metals.live/
you get the error massage 502 Bad Gateway

If you could find a fix for it, that would be great. 

Thank you in advance

**Comment by Fifteen15Studios** [comment]
There is nothing I can do. This is the equivalent of saying "Github is down, fix it!" There's nothing for me to fix. The API is down. It has been for days, maybe weeks. I don't know who runs the API, and therefore don't have a way to contact them. I have looked for other free alternatives and have not found any. 

If you can find a free alternative, feel free to post it here and I can attempt to change the code to use a different API. But unless another free metals API is found, we're at the mercy of whoever runs metals.live

**Comment by johnso515** [comment]
Have you looked at https://rapidapi.com/solutionsbynotnull/api/live-metal-prices/pricing (50/mo free) or https://metals.dev/pricing (250/mo free)?  Daily or 2/x daily would be better than nothing.  I have used other APIs through rapidapi and have not had any trouble.  Of course, both would require the user to get an API key.

**Comment by Fifteen15Studios** [comment]
I have updated to use api.metals.dev. New version is available. ReadMe has been updated to reflect the new changes.
